import img from "../../../../images/landing/bth.jpg";
import { v4 as uuidv4 } from "uuid";

export const LANDING_SERVICE_DATA = [
  {
    id: uuidv4(),
    title: "driver",
    des: "des1",
    img: img,
    containerClass: "",
    imgClass: "",
    textClass: "",
    href: "/drivers",
  },
  {
    id: uuidv4(),
    title: "tourGuide",
    des: "des2",
    img: img,
    containerClass: "",
    imgClass: "md:order-2",
    textClass: "md:order-1 items-end",
    href: "/tour-guide",
  },
  {
    id: uuidv4(),
    title: "career",
    des: "des3",
    img: img,
    containerClass: "",
    imgClass: "",
    textClass: "",
    href: "/career",
  },
  {
    id: uuidv4(),
    title: "villa",
    des: "des4",
    img: img,
    containerClass: "",
    imgClass: "md:order-2",
    textClass: "md:order-1 items-end",
    href: "/villa",
  },
  {
    id: uuidv4(),
    title: "homestay",
    des: "des5",
    img: img,
    containerClass: "",
    imgClass: "",
    textClass: "",
    href: "/homestay",
  },
  {
    id: uuidv4(),
    title: "hotel",
    des: "des6",
    img: img,
    containerClass: "",
    imgClass: "md:order-2",
    textClass: "md:order-1 items-end",
    href: "/hotel",
  },
  {
    id: uuidv4(),
    title: "resort",
    des: "des7",
    img: img,
    containerClass: "",
    imgClass: "",
    textClass: "",
    href: "/resort",
  },
];
